forum/urls.py
from django.urls import path

from forum import views

app_name = 'forum'

urlpatterns = [
    path('', views.ForumListView.as_view(), name='forum-list'),
    path('<int:pk>/detail/', views.ForumDetailView.as_view(), name='forum-detail'),
    path('<int:forum_pk>/topic/add/', views.TopicCreateView.as_view(), name='topic-add'),
    path('<int:forum_pk>/topic/<int:topic_pk>/detail/',
         views.TopicDetailView.as_view(), name='topic-detail'),
    path('<int:forum_pk>/topic/<int:topic_pk>/comment/add/',
         views.CommentCreateView.as_view(), name='comment-add'),

]

genoskul/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView
from us.views import PrivacyTemplateView, TermOfServiceTemplateView, AboutTemplateView
from genoskul.views import HomeTemplateView
from filebrowser.sites import site

admin.site.site_header = 'Site d\'administration de GENOSKUL'
admin.site.index_title = 'Panel administration GENOSKUL'
admin.site.site_title = 'GENOSKUL Admin'


urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('privacy/', PrivacyTemplateView.as_view(), name='privacy'),
    path('terms/', TermOfServiceTemplateView.as_view(), name='terms'),
    path('about/', AboutTemplateView.as_view(), name='about'),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),
    path('registration/', include('accounts.urls', namespace="accounts")),
    path('jobs/', include('jobs.urls', namespace="jobs")),
    path('learning/', include('learning.urls', namespace="learning")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('ndjor/', include('ndjor.urls', namespace="ndjor")),
    path('forum/', include('forum.urls', namespace="forum")),
    path('services/', include('services.urls', namespace="services")),
    path('admin/filebrowser/', site.urls),
    path('admin/staff/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path

from jobs.views import *

app_name = 'jobs'

urlpatterns = [
    path('list/',
         JobListView.as_view(), name='job-list'),
    path('resumes/list/', ResumeListView.as_view(), name='resume-list'),
    path('category/list/', CategoryListView.as_view(), name='category-list'),
    path('category/<int:pk>/detail/',
         CategoryDetailView.as_view(), name='category-detail'),
    path('resumes/<int:pk>/detail/',
         ResumeDetailView.as_view(), name='resume-detail'),
    path('<int:pk>/detail/', JobDetailView.as_view(), name='job-detail'),
]

forum/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

from genoskul.common.timestamp import TimeStampModel
from forum.managers import CommentManager, ForumManager

User = get_user_model()


class Forum(TimeStampModel):
    name = models.CharField(max_length=50, verbose_name='Nom du forum')
    description = models.TextField(
        blank=True, verbose_name='Description du forum')
    logo = models.ImageField(blank=True, null=True, upload_to='forums/logos/')
    visibility = models.CharField(max_length=20, default='private', choices=(
        ('private', 'Privé'), ('public', 'Public')), verbose_name='Visibilité')

    objects = ForumManager()

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('forum:forum-detail', kwargs={'pk': self.pk})

    # def comments_count(self):
    #     return


class ForumRegistration(TimeStampModel):
    date = models.DateField(verbose_name='Date d\'inscription au forum', auto_now=True)
    is_admin = models.BooleanField(default=False, verbose_name='admin ?')
    forum = models.ForeignKey(
        Forum, on_delete=models.CASCADE, related_name='members')
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='forums')

    def __str__(self):
        return self.forum.name


class Topic(TimeStampModel):
    title = models.CharField(max_length=254, verbose_name='Titre')
    detail = models.TextField(verbose_name='Commentaire')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE,
        verbose_name='Auteur',
        related_name='my_topics')
    forum = models.ForeignKey(
        Forum, on_delete=models.CASCADE,
        verbose_name='Forum',
        related_name='topics')

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.title

    # def get_absolute_url(self):
    #     return reverse('forum:topic-detail', kwargs={'fo'})

    def get_last_replied(self):
        replies = Comment.objects.get_comments_by_topic(self.pk)
        return replies.first()

    def get_last_replied_user(self):
        last_replied = self.get_last_replied()
        return last_replied.author if last_replied else None

    def get_last_replied_date(self):
        last_replied = self.get_last_replied()
        return last_replied.created_at if last_replied else None


class Comment(TimeStampModel):
    content = models.TextField(verbose_name='Contenu du commentaire')
    author = models.ForeignKey(
        User, on_delete=models.CASCADE,
        verbose_name='Auteur du commentaire',
        related_name='my_comments')

    topic = models.ForeignKey(
        Topic, on_delete=models.CASCADE,
        verbose_name='Sujet',
        related_name='comments')

    objects = CommentManager()

    class Meta:
        ordering = ('-created_at',)

    def __str__(self):
        return self.content

forum/forms.py
from django import forms

from forum.models import Comment, Topic


class TopicModelForm(forms.ModelForm):
    class Meta:
        model = Topic
        exclude = ('author', 'forum')


class CommentModelForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('author', 'topic')

forum/views.py
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView, CreateView
from django.contrib.messages.views import SuccessMessageMixin
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse

from forum.models import Forum, ForumRegistration, Topic, Comment
from forum.forms import TopicModelForm, CommentModelForm


class ForumListView(LoginRequiredMixin, ListView):
    template_name = 'forum/forum-list.html'
    model = Forum
    context_object_name = 'forums'

    def get_queryset(self):
        return self.request.user.forums.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['public_forums'] = Forum.objects.get_not_registered_public_forums_by_user(
            self.request.user)
        return context


class ForumDetailView(LoginRequiredMixin, DetailView):
    template_name = 'forum/forum-detail.html'
    model = Forum
    context_object_name = 'forum'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['registrations'] = self.request.user.forums.all()
        return context


class TopicDetailView(LoginRequiredMixin, DetailView):
    template_name = 'forum/topic-detail.html'
    model = Topic
    context_object_name = 'topic'

    def get_object(self):
        topic_pk = self.kwargs.get('topic_pk')
        return get_object_or_404(self.model, pk=topic_pk)


class TopicCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'forum/form.html'
    form_class = TopicModelForm
    success_message = 'Votre sujet a été ajouté'

    def get_context_data(self, **kwargs: any) -> dict:
        context = super().get_context_data(**kwargs)
        context['forum_pk'] = kwargs.get('forum_pk')
        return context

    def get_success_url(self):
        return reverse(
            'forum:forum-detail',
            kwargs={'pk': self.kwargs.get('forum_pk')})

    def get_forum_object(self):
        return get_object_or_404(
            Forum,
            pk=self.kwargs.get('forum_pk'))

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.forum = self.get_forum_object()

        obj.save()

        return super().form_valid(form)


class CommentCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'forum/form.html'
    form_class = CommentModelForm
    success_message = 'Votre commentaire a été ajouté'

    def get_success_url(self):
        return reverse('forum:topic-detail', kwargs={
            'forum_pk': self.kwargs.get('forum_pk'),
            'topic_pk': self.kwargs.get('topic_pk')
        })

    def get_topic_object(self):
        return get_object_or_404(Topic, pk=self.kwargs.get('topic_pk'))

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.author = self.request.user
        obj.topic = self.get_topic_object()

        obj.save()

        return super().form_valid(form)

forum/templates/forum/detail.html
{% load static %}
{% load humanize %}

<div id="dashboard">
    <div class="container">

        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="main-body p-0 margin-top-30">
                    <div class="inner-wrapper">
                        <div class="inner-sidebar">
                            <div class="inner-sidebar-header justify-content-center">
                                <a href="{% url 'forum:topic-add' forum_pk=forum.pk %}" class="btn btn-primary">Nouveau
                                    sujet</a>
                            </div>

                            <div class="inner-sidebar-body p-0">
                                <div class="p-3 h-100" data-simplebar="init">
                                    <div class="simplebar-wrapper" style="margin: -16px;">
                                        <div class="simplebar-height-auto-observer-wrapper">
                                            <div class="simplebar-height-auto-observer"></div>
                                        </div>
                                        <div class="simplebar-mask">
                                            <div class="simplebar-offset" style="right: 0px; bottom: 0px;">
                                                <div class="simplebar-content-wrapper" style="height: 100%;">
                                                    <div class="simplebar-content" style="padding: 16px;">
                                                        <p>Tous mes forums</p>
                                                        <nav class="nav nav-pills nav-gap-y-1 flex-column">
                                                            {% for registration in registrations %}
                                                            {% with registration.forum as my_forum %}
                                                            <li>

                                                                <a href="{{my_forum.get_absolute_url}}" class="nav-link nav-link-faded has-icon {% if my_forum.pk == forum.pk %}
                                                                      active
                                                                    {% endif %}">{{my_forum}}</a>

                                                            </li>
                                                            {% endwith %}

                                                            {% endfor %}

                                                        </nav>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="simplebar-placeholder" style="width: 234px; height: 292px;"></div>
                                    </div>
                                    <div class="simplebar-track simplebar-horizontal" style="visibility: hidden;">
                                        <div class="simplebar-scrollbar" style="width: 0px; display: none;"></div>
                                    </div>
                                    <div class="simplebar-track simplebar-vertical" style="visibility: visible;">
                                        <div class="simplebar-scrollbar"
                                            style="height: 151px; display: block; transform: translate3d(0px, 0px, 0px);">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="inner-main">
                            <div class="inner-main-header">
                                <a href="{% url 'forum:forum-list' %}"> <i class="fa fa-arrow-circle-left"></i> Quitter
                                    le forum</a>
                            </div>

                            <div class="inner-main-body p-2 p-sm-3 collapse forum-content show">
                                <div class="d-md-none d-lg-none ">
                                    <a href="{% url 'forum:topic-add' forum_pk=forum.pk %}"
                                        class="btn btn-primary mb-2">Nouveau
                                        sujet</a>
                                </div>

                                <div class="d-sm-none alert alert-primary">
                                    Les sujets qui ont été discutés dans le groupe. Cliquez en sur un
                                    pour lire les interventions
                                </div>
                                <div class="card mb-2">
                                    <div class="card-body p-2 p-sm-3">
                                        {% for topic in forum.topics.all %}
                                        <div class="media forum-item">
                                            <a
                                                href="{% url 'forum:topic-detail' forum_pk=forum.pk topic_pk=topic.pk %}"><img
                                                    src="{% static 'images/avatar-placeholder.png' %}"
                                                    class="mr-3 rounded-circle"
                                                    style="width: 50px !important; height: 50px !important;"
                                                    alt="User" /></a>
                                            <div class="media-body">
                                                <h6><a href="{% url 'forum:topic-detail' forum_pk=forum.pk topic_pk=topic.pk %}"
                                                        class="text-primary">{{topic.title}}</a></h6>
                                                <p class="text-secondary">
                                                    {{topic.detail|truncatewords:20}}
                                                </p>
                                                {% if topic.get_last_replied %}
                                                <p class="text-muted"><a
                                                        href="javascript:void(0)">{{topic.get_last_replied_user}}</a> a
                                                    répondu
                                                    <span
                                                        class="text-secondary font-weight-bold">{{topic.get_last_replied_date|naturalday}}</span>
                                                </p>
                                                {% endif %}
                                            </div>
                                            <div class="text-muted small text-center align-self-center">

                                                <span><i class="fa fa-comment ml-2"></i> {{topic.comments.count}}</span>
                                            </div>
                                        </div>
                                        {% empty %}
                                        <p class="text">Auncun sujet n'a été créé. Pourquoi ne pas en créer un ? <a
                                                href="{% url 'forum:topic-add' forum_pk=forum.pk %}">Créer un sujet de
                                                discussion</a></p>
                                        {% endfor %}
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

forum/templates/forum/form.html
{% extends "forum/base.html" %}

{% load crispy_forms_tags %}


{% block content %}
<div id="dashboard">
    <div class="container">

        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="main-body p-0 margin-top-30">
                    <div class="inner-wrapper">
                        <div class="inner-sidebar">
                            <div class="inner-sidebar-header justify-content-center">
                                <a href="" class="btn btn-primary">Nouveau sujet</a>
                            </div>

                            <div class="inner-sidebar-body p-0">
                                <div class="p-3 h-100" data-simplebar="init">
                                    <div class="simplebar-wrapper" style="margin: -16px;">
                                        <div class="simplebar-height-auto-observer-wrapper">
                                            <div class="simplebar-height-auto-observer"></div>
                                        </div>
                                        <div class="simplebar-mask">
                                            <div class="simplebar-offset" style="right: 0px; bottom: 0px;">
                                                <div class="simplebar-content-wrapper" style="height: 100%;">
                                                    <div class="simplebar-content" style="padding: 16px;">
                                                        <p>Tous mes forums</p>
                                                        <nav class="nav nav-pills nav-gap-y-1 flex-column">
                                                            {% for registration in registrations %}
                                                            {% with registration.forum as my_forum %}
                                                            <li>

                                                                <a href="{{my_forum.get_absolute_url}}"
                                                                    class="nav-link nav-link-faded has-icon {% if my_forum.pk == forum.pk %}
                                                                      active
                                                                    {% endif %}">{{my_forum}}</a>

                                                            </li>
                                                            {% endwith %}

                                                            {% endfor %}

                                                        </nav>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="simplebar-placeholder" style="width: 234px; height: 292px;"></div>
                                    </div>
                                    <div class="simplebar-track simplebar-horizontal" style="visibility: hidden;">
                                        <div class="simplebar-scrollbar" style="width: 0px; display: none;"></div>
                                    </div>
                                    <div class="simplebar-track simplebar-vertical" style="visibility: visible;">
                                        <div class="simplebar-scrollbar"
                                            style="height: 151px; display: block; transform: translate3d(0px, 0px, 0px);">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="inner-main">
                            <div class="inner-main-header">
                                <a href="{% url 'forum:forum-list' %}"> <i class="fa fa-arrow-circle-left"></i> Quitter le forum</a>
                                
                            </div>

                            <div class="inner-main-body p-2 p-sm-3 collapse forum-content show">
                                <div class="card mb-2">
                                    <div class="card-body p-2 p-sm-3">
                                     <form method="post">
                                        {% csrf_token %}
                                        {{form|crispy}}
                                        <button type="submit" class="btn btn-primary">Ajouter</button>
                                     </form>
                                    </div>
                                </div>

                          
                            </div>



                        </div>

                    </div>

                 
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

forum/templates/forum/topic-detail.html
{% extends "forum/base.html" %}

{% load static %}
{% load humanize %}

{% block content %}
<div id="dashboard">
    <div class="container">

        <div class="row">
            <div class="col-lg-12 col-md-12">
                <div class="main-body p-0 margin-top-30">
                    <div class="inner-wrapper">
                        <div class="inner-sidebar">
                            <div class="inner-sidebar-header">
                                Forum : &ensp; <span class="text-primary text-uppercase" >{{topic.forum}}</span>
                            </div>

                            <div class="inner-sidebar-body p-0">
                                <div class="p-3 h-100" data-simplebar="init">
                                    <div class="simplebar-wrapper" style="margin: -16px;">
                                        <div class="simplebar-height-auto-observer-wrapper">
                                            <div class="simplebar-height-auto-observer"></div>
                                        </div>
                                        <div class="simplebar-mask">
                                            <div class="simplebar-offset" style="right: 0px; bottom: 0px;">
                                                <div class="simplebar-content-wrapper" style="height: 100%;">
                                                    <div class="simplebar-content" style="padding: 16px;">
                                                        <p>Tous les sujets</p>
                                                        <nav class="nav nav-pills nav-gap-y-1 flex-column">
                                                            {% for t in topic.forum.topics.all %}
                                                            <li>

                                                                <a href="{% url 'forum:topic-detail' forum_pk=topic.forum.pk topic_pk=t.pk %}"
                                                                    class="nav-link nav-link-faded text-primary has-icon {% if t.pk == topic.pk %}
                                                                      active
                                                                    {% endif %}">{{t}} &ensp; <i class="fa fa-arrow-right"></i></a>
                                                            </li>

                                                            {% endfor %}

                                                        </nav>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                        <div class="simplebar-placeholder" style="width: 234px; height: 292px;"></div>
                                    </div>
                                    <div class="simplebar-track simplebar-horizontal" style="visibility: hidden;">
                                        <div class="simplebar-scrollbar" style="width: 0px; display: none;"></div>
                                    </div>
                                    <div class="simplebar-track simplebar-vertical" style="visibility: visible;">
                                        <div class="simplebar-scrollbar"
                                            style="height: 151px; display: block; transform: translate3d(0px, 0px, 0px);">
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="inner-main">
                            <div class="inner-main-header">
                                <a href="{{topic.forum.get_absolute_url}}" class=""> <i class="fa fa-arrow-circle-left"></i>  Quitter la file de discussions</a>
                                <!-- <span class="input-icon input-icon-sm ml-auto w-auto">
                                    <input type="text"
                                        class="form-control form-control-sm bg-gray-200 border-gray-200 shadow-none mb-4 mt-4"
                                        placeholder="Search forum" />
                                </span> -->
                            </div>

                            <div class="inner-main-body p-2 p-sm-3 collapse forum-content show">
                                {% if messages %}
                                  {% for message in messages %}
                                  <div class="alert alert-success">
                                    {{message}}
                                </div>
                                  {% endfor %}
                                {% endif %}
                                <div class="card mb-2">
                                    <div class="card-body p-2 p-sm-3">
                                        <div class="media forum-item">
                                            <a href="#" data-toggle="collapse" data-target=".forum-content"><img
                                                    src="{% static 'images/avatar-placeholder.png' %}"
                                                    class="mr-3 rounded-circle"
                                                    style="width: 50px !important; height: 50px !important;"
                                                    alt="User" /></a>
                                            <div class="media-body">
                                                <h6><a href="#" data-toggle="collapse" data-target=".forum-content"
                                                        class="text-body">{{topic.title}}</a></h6>
                                                <p class="text-secondary">
                                                    {{topic.detail|truncatewords:20}}
                                                </p>
                                                {% if topic.get_last_replied %}
                                                <p class="text-muted"><a href="javascript:void(0)">{{topic.get_last_replied_user}}</a> a répondu
                                                    <span class="text-secondary font-weight-bold">{{topic.get_last_replied_date|naturalday}}</span>
                                                </p>
                                                {% endif %}
                                            </div>
                                            <div class="text-muted small text-center align-self-center">
                                                <span class="d-none d-sm-inline-block"><i class="fa fa-eye"></i>
                                                    19</span>
                                                <span><i class="fa fa-comment ml-2"></i> {{topic.comments.count}}</span>
                                            </div>
                                            
                                        
                                        <a href="{% url 'forum:comment-add' forum_pk=topic.forum.pk topic_pk=topic.pk %}" class="btn btn-primary btn-sm">Commentez</a>

                                        </div>
                                        <p>Interventions ({{topic.comments.count}})</p>
                                       
                                        {% for comment in topic.comments.all %}
                                        <div class="media forum-item">
                                            <a href="#"><img
                                                    src="{% static 'images/avatar-placeholder.png' %}"
                                                    class="mr-3 rounded-circle"
                                                    style="width: 50px !important; height: 50px !important;"
                                                    alt="User" /></a>
                                            <div class="media-body">
                                               
                                                <p class="text-secondary">
                                                    {{comment.content}}
                                                </p>
                                                <p class="text-muted">{{comment.created_at|naturalday}}</p>
                                            </div>
                                            
                                        </div>
                                        {% endfor %}
                                    </div>
                                </div>

                                <!-- <ul class="pagination pagination-sm pagination-circle justify-content-center mb-0">
                                    <li class="page-item disabled">
                                        <span class="page-link has-icon"><i
                                                class="material-icons">chevron_left</i></span>
                                    </li>
                                    <li class="page-item"><a class="page-link" href="javascript:void(0)">1</a></li>
                                    <li class="page-item active"><span class="page-link">2</span></li>
                                    <li class="page-item"><a class="page-link" href="javascript:void(0)">3</a></li>
                                    <li class="page-item">
                                        <a class="page-link has-icon" href="javascript:void(0)"><i
                                                class="material-icons">chevron_right</i></a>
                                    </li>
                                </ul> -->
                            </div>

                        </div>

                    </div>

                    </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}