accounts/urls.py
from django.urls import path, include
from accounts.views import *


app_name = 'accounts'

urlpatterns = [
    #path('', include('templates.urls')),
    path('profile/completion/', ProfileCompletionUpdateView.as_view(),
         name='profile-completion'),
    path('register/', SignupView.as_view(), name='register'),
    path('user/<int:pk>/update/', UserInfoUpdateView.as_view(),
         name='user_info-update'),
]

dashboard/urls.py
from django.urls import path

from dashboard.views import *
from accounts.views import ProfileUpdateView
from ndjor.views import ProductCreateView, ProductUpdateView
from learning.views import DocumentCreateView
# from jobs.views import

app_name = 'dashboard'

urlpatterns = [
    path('', DashboardTemplateView.as_view(), name='dashboard'),
    path('documents/',
         DashboardDocumentListView.as_view(),
         name='documents'),
    path('document/create/',
         DocumentCreateView.as_view(),
         name='document-create'),

    path('document/<int:pk>/delete/',
         DashboardDocumentDeleteView.as_view(),
         name='document-delete'),

    path('products/<int:pk>/delete/',
         DashboardProductDeleteView.as_view(),
         name='product-delete'),

    path('posts/<int:pk>/delete/',
         DashboardPostDeleteView.as_view(),
         name='post-delete'),

    path('jobs/create/',
         DashboardJobCreateView.as_view(),
         name='job-create'),

    path('job/<int:pk>/update/',
         DashboardJobUpdateView.as_view(),
         name='job-update'),

    path('jobs/list/',
         DashboardJobsListView.as_view(),
         name='jobs-list'),

    path('resume/add/',
         DashboardResumeCreateView.as_view(),
         name='resume-create'),

    path('resume/<int:pk>/update/',
         DashboardResumeUpdateView.as_view(),
         name='resume-update'),

    path('product/create/',
         ProductCreateView.as_view(),
         name='product-create'),

    path('product/<int:pk>/update/',
         ProductUpdateView.as_view(),
         name='product-update'),

    path('services/create/',
         DashboardServiceCreateView.as_view(),
         name='service-create'),

    path('product/list/',
         DashboardProductListView.as_view(),
         name='products'),

    path('profile/update/',
         ProfileUpdateView.as_view(),
         name='profile-update'),

    path('posts/create/',
         DashboardPostCreateView.as_view(),
         name='post-create'),

    path('post/list/', DashboardPostListView.as_view(), name='posts'),
]

forum/urls.py
from django.urls import path

from forum import views

app_name = 'forum'

urlpatterns = [
    path('', views.ForumListView.as_view(), name='forum-list'),
    path('<int:pk>/detail/', views.ForumDetailView.as_view(), name='forum-detail'),
    path('<int:forum_pk>/topic/add/', views.TopicCreateView.as_view(), name='topic-add'),
    path('<int:forum_pk>/topic/<int:topic_pk>/detail/',
         views.TopicDetailView.as_view(), name='topic-detail'),
    path('<int:forum_pk>/topic/<int:topic_pk>/comment/add/',
         views.CommentCreateView.as_view(), name='comment-add'),

]

genoskul/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView
from us.views import PrivacyTemplateView, TermOfServiceTemplateView, AboutTemplateView
from genoskul.views import HomeTemplateView
from filebrowser.sites import site

admin.site.site_header = 'Site d\'administration de GENOSKUL'
admin.site.index_title = 'Panel administration GENOSKUL'
admin.site.site_title = 'GENOSKUL Admin'


urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('privacy/', PrivacyTemplateView.as_view(), name='privacy'),
    path('terms/', TermOfServiceTemplateView.as_view(), name='terms'),
    path('about/', AboutTemplateView.as_view(), name='about'),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),
    path('registration/', include('accounts.urls', namespace="accounts")),
    path('jobs/', include('jobs.urls', namespace="jobs")),
    path('learning/', include('learning.urls', namespace="learning")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('ndjor/', include('ndjor.urls', namespace="ndjor")),
    path('forum/', include('forum.urls', namespace="forum")),
    path('services/', include('services.urls', namespace="services")),
    path('admin/filebrowser/', site.urls),
    path('admin/staff/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path

from jobs.views import *

app_name = 'jobs'

urlpatterns = [
    path('list/',
         JobListView.as_view(), name='job-list'),
    path('resumes/list/', ResumeListView.as_view(), name='resume-list'),
    path('category/list/', CategoryListView.as_view(), name='category-list'),
    path('category/<int:pk>/detail/',
         CategoryDetailView.as_view(), name='category-detail'),
    path('resumes/<int:pk>/detail/',
         ResumeDetailView.as_view(), name='resume-detail'),
    path('<int:pk>/detail/', JobDetailView.as_view(), name='job-detail'),
]

dashboard/models.py
from django.db import models

# Create your models here.

ndjor/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth import get_user_model
from genoskul.common.timestamp import TimeStampModel
from django.urls import reverse

User = get_user_model()


class ProductManager(models.Manager):
    def get_products(self, query=None):
        qs = self.get_queryset()
        if query:
            return qs.filter(
                Q(name__icontains=query) |
                Q(state__icontains=query) |
                Q(reference__icontains=query) |
                Q(location__icontains=query) |
                Q(price__icontains=query)
            )

        return qs



class ProductCategory(TimeStampModel):
    name = models.CharField(max_length=200, verbose_name='Nom de la catégorie')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("ndjor:category-details", kwargs={"pk": self.pk})
    
    class Meta:
        verbose_name = 'Catégorie de produit'
        verbose_name_plural = 'Catégories des produits'

class Product(TimeStampModel):
    name = models.CharField(max_length=100, verbose_name='Nom du produit')
    state = models.CharField(max_length=30, choices=(
        ('new', 'Neuf'), ('like_new', 'Comme Neuf'), ('others', 'Autres')), verbose_name='Etat du produit')
    category = models.ForeignKey(
        ProductCategory, on_delete=models.CASCADE, verbose_name='Catégorie du produit', related_name='products')
    reference = models.CharField(
        max_length=254, verbose_name='Contact du vendeur')
    image = models.ImageField(verbose_name='Photo de produit')
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='products', verbose_name='Propriétaire')
    location = models.CharField(max_length=30, verbose_name='Lieu de vente')
    price = models.CharField(max_length=30, blank=True, verbose_name='Prix' )

    objects = ProductManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Produit'
        verbose_name_plural = 'Produits'

dashboard/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    ListView,
    CreateView,
    TemplateView,
    UpdateView,
    DeleteView
)

from jobs.forms import JobModelForm, ResumeModelForm
from jobs.models import Company, Job, Resume
from learning.models import Document
from services.forms import ServiceModelForm
from services.models import Box
from ndjor.models import Product
from blog.models import Post


class DashboardTemplateView(LoginRequiredMixin, TemplateView):
    template_name = 'dashboard/dashboard.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        return context


class DashboardDocumentListView(LoginRequiredMixin, ListView):
    model = Document
    context_object_name = 'documents'
    template_name = 'dashboard/documents.html'
    paginate_by = 10

    def get_queryset(self):
        return self.request.user.documents.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Mes documents'
        return context


class DashboardDocumentDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'dashboard/delete-confirm.html'
    model = Document
    success_url = reverse_lazy('dashboard:documents')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Suppression'
        context['previous_path'] = self.request.META.get('HTTP_REFERER')
        return context


class DashboardProductDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'dashboard/delete-confirm.html'
    model = Product
    success_url = reverse_lazy('dashboard:products')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Suppression'
        context['previous_path'] = self.request.META.get('HTTP_REFERER')
        return context


class DashboardPostDeleteView(LoginRequiredMixin, DeleteView):
    template_name = 'dashboard/delete-confirm.html'
    model = Product
    success_url = reverse_lazy('dashboard:posts')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Suppression'
        context['previous_path'] = self.request.META.get('HTTP_REFERER')
        return context

class DashboardJobCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    form_class = JobModelForm
    template_name = 'dashboard/job-create.html'
    success_url = reverse_lazy('dashboard:job-create')
    success_message = 'Votre offre a été ajoutée avec succès !'

    def form_valid(self, form):
        data = form.cleaned_data
        company = Company.objects.create(
            name=data.get('company_name'),
            website=data.get('website'),
            logo=form.files.get('logo'),
            tagline=data.get('tagline'),
        )
        obj = form.save(commit=False)
        obj.company = company
        obj.user = self.request.user
        obj.save()
        return super().form_valid(form)


class DashboardResumeCreateView(
        LoginRequiredMixin,
        SuccessMessageMixin,
        CreateView):
    template_name = 'dashboard/profile-add.html'
    form_class = ResumeModelForm
    success_url = reverse_lazy('dashboard:resume-create')
    success_message = 'Votre CV a été déposé avec succès !'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ajouter un CV'
        return context

    def form_invalid(self, form):
        print(form.errors)
        return super().form_invalid(form)

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.user = self.request.user
        print(form.data)
        obj.save()
        return super().form_valid(form)


class DashboardResumeUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = 'dashboard/profile-add.html'
    form_class = ResumeModelForm
    success_message = 'Votre CV a été bien mis à jour !'
    success_url = reverse_lazy('dashboard:resume-update')

    def get_object(self):
        return get_object_or_404(Resume, pk=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Modifier votre CV'
        return context


class DashboardJobUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = 'dashboard/job-create.html'
    model = Job
    form_class = JobModelForm
    context_object_name = 'job'
    success_message = 'Votre offre d\'emploi a été modifiée avec succès !'

    def get_success_url(self):
        return reverse('dashboard:job-update', kwargs={'pk': self.kwargs.get('pk')})

    def get_initial(self):
        company = self.get_object().company
        initial = super().get_initial()
        initial.update({
            'company_name': company.name,
            'website': company.website,
            'logo': company.logo,
            'tagline': company.tagline
        })
        return initial

    def form_valid(self, form):
        data = form.data
        obj = form.save()
        company = obj.company
        print(data)
        company.name = data.get('company_name')
        company.website = data.get('website')
        company.tagline = data.get('tagline')
        company.logo = form.files.get('logo')
        company.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Modification de l\'offre d\'emploi'
        return context


class DashboardProductListView(LoginRequiredMixin, ListView):
    template_name = 'dashboard/products.html'
    context_object_name = 'products'

    def get_queryset(self):
        return self.request.user.products.all()


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Mes produits'
        return context

class DashboardServiceCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'services/service-form.html'
    form_class = ServiceModelForm
    success_url = reverse_lazy('dashboard:dashboard')
    success_message = "Votre demande a été bien reçu,vous recevrez un mail pour confirmer votre demande. Restez connecter avec genoskul "

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.owner = self.request.user
        obj.save()
        return super().form_valid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Créer un service'
        return context
        
# class DashboardServiceCreateView(LoginRequiredMixin, SuccessMessageMixin, Update):
#     template_name = 'services/service-form.html'
#     form_class = ServiceModelForm
#     success_url = reverse_lazy('dashboard:service-update')
#     success_message = "Votre demande a été bien reçu, veuillez patienter pendant que nous validons! "

#     def get_object(self):
#         return get_object_or_404(Box, pk=self.kwargs.get('pk'))

#     def get_context_data(self):
#         context = super().get_context_data(**kwargs)
#         context['title'] = 'Modifier votre demande'


class DashboardJobsListView(LoginRequiredMixin, ListView):
    template_name = 'dashboard/jobs.html'
    model = Job
    context_object_name = 'jobs'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Liste des offres d\'emploi'
        return context


class DashboardPostCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'dashboard/post-form.html'
    model = Post
    fields = ('title', 'category', 'image', 'content')
    success_message = 'Votre post a été ajouté avec succès !'
    success_url = reverse_lazy('dashboard:post-create')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Poster'
        return context
    
    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.creator = self.request.user
        obj.save()
        return super().form_valid(form)


class DashboardPostListView(LoginRequiredMixin, ListView):
    template_name = 'dashboard/posts.html'
    model = Post
    context_object_name = 'posts'
    paginate_by = 10

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Posts crées'
        return context

dashboard/templates/dashboard/base.html
{% extends "base.html" %}

{% block title %}
Tableau de bord
{% endblock title %}


{% block extrastyles %}
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css"
	integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">

{% endblock extrastyles %}

{% block navbar %}
{% include "base/headers/navbar-dashboard.html" %}
{% endblock navbar %}

{% block content %}


<!-- {% url 'dashboard:jobs-list' as jobs_list_url %}
{% url 'dashboard:job-create' as job_create_url %} -->
{% url 'dashboard:documents' as documents_url %}
{% url 'dashboard:document-create' as document_create_url %}
{% url 'dashboard:products' as products_url %}
{% url 'dashboard:product-create' as product_create_url %}
{% url 'dashboard:dashboard' as dashboard_url %}
{% url 'dashboard:profile-update' as profile_url %}
{% url 'dashboard:post-create' as post_create_url %}
{% url 'dashboard:posts' as posts_url %}
{% url 'forum:forum-list' as forum_list_url %}

{% url 'accounts:user_info-update' pk=request.user as user_info_update_url %}

<div id="dashboard">


	<a href="#" class="dashboard-responsive-nav-trigger"><i class="fa fa-reorder"></i> Mes Infos</a>

	<div class="dashboard-nav">
		<div class="dashboard-nav-inner">

			<ul data-submenu-title="Espace d'étudiants">
				<li><a href="{{forum_list_url}}">Forums</a></li>
				
				
			</ul>

			{% with request.user as user %}
			<ul data-submenu-title="Gérer">
				<li><a>Documents</a>
					<ul>
						<li><a href="{{documents_url}}">Mes documents <span
									class="nav-tag">{{user.documents.count}}</span></a></li>
						<li><a href="{{document_create_url}}">Publier un document</a></li>
					</ul>
				</li>
				<li><a>Posts</a>
					<ul>
						<li><a href="{{posts_url}}">Mes Posts <span
									class="nav-tag">{{user.posts.count}}</span></a></li>
						<li><a href="{{post_create_url}}">Publier un post</a></li>
					</ul>
				</li>
				<li><a>Produits</a>
					<ul>
						<li><a href="{{products_url}}">Mes produits <span
									class="nav-tag">{{user.products.count}}</span></a></li>
						<li><a href="{{product_create_url}}">Ajouter un produit</a></li>
					</ul>
				</li>
				
				{% with request.user.resumes.first as resume %}
				<li><a href="{% if resume %}
					{% url 'dashboard:resume-update' pk=resume.pk %}
					{% else %}
					{% url 'dashboard:resume-create' %}
				  {% endif %}">Créer profil</a>
				  </li>
				{% endwith %}
				
			</ul>

			{% endwith %}
			<ul data-submenu-title="Compte">
				<li><a href="{{profile_url}}">Mon profil</a></li>
				<li><a href="{% url 'account_change_password' %}">Securité</a></li>
				<li><a href="{% url 'accounts:user_info-update' pk=request.user.pk %}">Perso</a></li>
			</ul>

		</div>
	</div>

	<div class="dashboard-content">

		<div id="titlebar" class="d-none d-md-block">
			<div class="row">
				<div class="col-md-12">
					<h2>Hello {{request.user.get_username}}</h2>
					<nav id="breadcrumbs">
						<ul>
							<li><a href="{{dashboard_url}}">Accueil</a></li>
							{% block breadcrumb %}

							{% endblock breadcrumb %}
						</ul>
					</nav>
				</div>
			</div>
		</div>

		{% if messages %}
		{% for message in messages %}
		<div class="notification {{message.tags}}">
			{{message}}
		</div>
		{% endfor %}
		{% endif %}
		{% block dashboard_content %}

		{% endblock dashboard_content %}

	</div>


</div>
{% endblock content %}

dashboard/templates/dashboard/delete-confirm.html
{% extends "dashboard/base.html" %}

{% block title %}
  {{title}}
{% endblock title %}

{% block breadcrumb %}
  <li>{{title}}</li>
{% endblock breadcrumb %}

{% block dashboard_content %}
  

    <div class="row">
        <div class="col-12">
            <form method="POST">
                <h3>Êtes-vous sûr ?</h3>
                <p>Voulez-vous vraiment supprimer l’objet utilisateur « {{object}} » ?</p>
                {% csrf_token %}
                <input type="hidden" value="Confirm">
                <a href="{{previous_path}}" class="btn btn-light">Annuler</a>
                <button type="submit" class="btn btn-danger">Continuer</button>
            </form>
        </div>
    </div>


{% endblock dashboard_content %}

dashboard/templates/dashboard/documents.html
{% extends "dashboard/base.html" %}

{% block title %}
{{title}}
{% endblock title %}

{% block breadcrumb %}
<li><a href="{% url 'dashboard:dashboard' %}">Tableau de bord</a></li>
<li>{{title}}</li>
{% endblock breadcrumb %}

{% block dashboard_content %}


<div class="row">

    <!-- Table-->
    <div class="col-lg-12 col-md-12">


        <div class="dashboard-list-box margin-top-30">
            <div class="dashboard-list-box-content">

                <!-- Table -->
                <table class="manage-table resumes responsive-table">

                    <tr>
                        <th><i class="fa fa-user"></i> Type</th>
                        <th><i class="fa fa-file-text"></i> Nom</th>
                        <th><i class="fa fa-download"></i> Téléchargements</th>
                        <th><i class="fa fa-calendar"></i> Création</th>
                        <th></th>
                    </tr>

                    <!-- Item #1 -->
                    {% for document in documents %}
                    <tr>
                        <td class="title"><a href="#">{{document.type}}</a></td>
                        <td>{{document.name}}</td>
                        <td>{{document.download_count}}</td>
                        <td>{{document.created_at}}</td>
                        <td class="action">
                            <!-- <a href="#"><i class="fa fa-pencil"></i> Editer</a> -->
                            <a href="{% url 'dashboard:document-delete' pk=document.pk %}"><i class="fa  fa-trash"></i>
                                Supprimer</a>
                            <!-- <a href="#" class="delete"><i class="fa fa-remove"></i> Supprimer</a> -->
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5" class="text-center">Vous n'avez publié aucun document. Cliquez sur le lien
                            suivant pour en publier un
                            <br><a href="{% url 'dashboard:document-create' %}">Publier un nouveau document</a></td>
                    </tr>
                    {% endfor %}

                    <!-- Item #1 -->


                </table>
            </div>
        </div>
    </div>
    {% include "dashboard/footer.html" %}
</div>
{% endblock dashboard_content %}

dashboard/templates/dashboard/footer.html
<div class="col-md-12">
    <div class="copyrights">© Copyright Genoskul 2020. Tous droits reservés.</div>
</div>

dashboard/templates/dashboard/jobs.html
{% extends "dashboard/base.html" %}

{% block title %}
{{title}}
{% endblock title %}

{% block breadcrumb %}
<li><a href="{% url 'dashboard:dashboard' %}">Tableau de bord</a></li>
<li>{{title}}</li>
{% endblock breadcrumb %}

{% block dashboard_content %}


<div class="row">

    <!-- Table-->
    <div class="col-lg-12 col-md-12">


        <div class="dashboard-list-box margin-top-30">
            <div class="dashboard-list-box-content">

                <!-- Table -->
                <table class="manage-table resumes responsive-table">

                    <tr>
                        <th><i class="fa fa-user"></i> Titre</th>
                        <th><i class="fa fa-file-text"></i> Type</th>
                        <th><i class="fa fa-download"></i> Date de fermeture</th>
                        <th><i class="fa fa-calendar"></i> Date création</th>
                        <th></th>
                    </tr>

                    <!-- Item #1 -->
                    {% for job in jobs %}
                    <tr>
                        <td class="title"><a href="{{job.get_absolute_url}}">{{job.title}}</a></td>
                        <td><span class="badge badge-primary">{{job.type}}</span></td>
                        <td>{{job.closing_date}}</td>
                        <td>{{job.created_at}}</td>
                        <td class="action">
                            <a href="{% url 'dashboard:job-update' pk=job.pk %}"><i class="fa fa-pencil"></i> Editer</a>
                            <a href="#"><i class="fa  fa-eye-slash"></i> Cacher</a>
                            <!-- <a href="#" class="delete"><i class="fa fa-remove"></i> Supprimer</a> -->
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5" class="text-center">Vous n'avez publié aucune offre. Cliquez sur le lien suivant pour en publier un
                            <br><a href="{% url 'learning:document-create' %}">Publier une offre d'emploi</a></td>
                    </tr>
                    {% endfor %}

                    <!-- Item #1 -->


                </table>
            </div>
        </div>
    </div>
    {% include "dashboard/footer.html" %}
</div>
{% endblock dashboard_content %}

dashboard/templates/dashboard/posts.html
{% extends "dashboard/base.html" %}

{% block title %}
{{title}}
{% endblock title %}

{% block breadcrumb %}
<li><a href="{% url 'dashboard:dashboard' %}">Tableau de bord</a></li>
<li>{{title}}</li>
{% endblock breadcrumb %}

{% block dashboard_content %}


<div class="row">

    <!-- Table-->
    <div class="col-lg-12 col-md-12">


        <div class="dashboard-list-box margin-top-30">
            <div class="dashboard-list-box-content">

                <!-- Table -->
                <table class="manage-table resumes responsive-table">

                    <tr>
                        <th><i class="fa fa-user"></i> #</th>
                        <th><i class="fa fa-file-text"></i> Titre</th>
                        
                        <th></th>
                    </tr>

                    <!-- Item #1 -->
                    {% for post in posts %}
                    <tr>
                        <td class="title"><a href="{{post.get_absolute_url}}">{{forloop.counter}}</a></td>
                        <td>{{post.title}}</td>
                      
                        <td class="action">
                            <!-- <a href="#"><i class="fa fa-pencil"></i> Editer</a> -->
                            <a href="{% url 'dashboard:post-delete' pk=post.pk %}"><i class="fa  fa-remove"></i> Supprimer</a>
                            <!-- <a href="#" class="delete"><i class="fa fa-remove"></i> Supprimer</a> -->
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5" class="text-center">Vous n'avez publié aucun post. Cliquez sur le lien suivant pour en publier un
                            <br><a href="{% url 'dashboard:post-create' %}">Publier un nouveau post</a></td>
                    </tr>
                    {% endfor %}

                    <!-- Item #1 -->


                </table>
            </div>
        </div>
    </div>
    {% include "dashboard/footer.html" %}
</div>
{% endblock dashboard_content %}

dashboard/templates/dashboard/products.html
{% extends "dashboard/base.html" %}

{% block title %}
{{title}}
{% endblock title %}

{% block breadcrumb %}
<li><a href="{% url 'dashboard:dashboard' %}">Tableau de bord</a></li>
<li>{{title}}</li>
{% endblock breadcrumb %}

{% block dashboard_content %}


<div class="row">

    <!-- Table-->
    <div class="col-lg-12 col-md-12">


        <div class="dashboard-list-box margin-top-30">
            <div class="dashboard-list-box-content">

                <!-- Table -->
                <table class="manage-table resumes responsive-table">

                    <tr>
                        <th><i class="fa fa-user"></i> Etat</th>
                        <th><i class="fa fa-file-text"></i> Nom</th>
                        <th><i class="fa fa-download"></i> Prix</th>
                        <th><i class="fa fa-calendar"></i> Création</th>
                        <th></th>
                    </tr>

                    <!-- Item #1 -->
                    {% for product in products %}
                    <tr>
                        <td class="title"><a href="#">{{product.get_state_display}}</a></td>
                        <td>{{product.name}}</td>
                        <td>{{product.price}}</td>
                        <td>{{product.created_at}}</td>
                        <td class="action">
                            <a href="{% url 'dashboard:product-update' pk=product.pk %}"><i class="fa fa-pencil"></i> Editer</a>
                            <!-- <a href="#"><i class="fa  fa-eye-slash"></i> Cacher</a> -->
                            <a href="{% url 'dashboard:product-delete' pk=product.pk %}" class="delete"><i class="fa fa-remove"></i> Supprimer</a>
                        </td>
                    </tr>
                    {% empty %}
                    <tr>
                        <td colspan="5" class="text-center">Vous n'avez publié aucun produit. Cliquez sur le lien suivant pour en publier un
                            <br><a href="{% url 'dashboard:product-create' %}">Publier un nouveau produit</a></td>
                    </tr>
                    {% endfor %}

                    <!-- Item #1 -->


                </table>
            </div>
        </div>
    </div>
    {% include "dashboard/footer.html" %}
</div>
{% endblock dashboard_content %}