dashboard/urls.py
from django.urls import path

from dashboard.views import *
from accounts.views import ProfileUpdateView
from ndjor.views import ProductCreateView, ProductUpdateView
from learning.views import DocumentCreateView
# from jobs.views import

app_name = 'dashboard'

urlpatterns = [
    path('', DashboardTemplateView.as_view(), name='dashboard'),
    path('documents/',
         DashboardDocumentListView.as_view(),
         name='documents'),
    path('document/create/',
         DocumentCreateView.as_view(),
         name='document-create'),

    path('document/<int:pk>/delete/',
         DashboardDocumentDeleteView.as_view(),
         name='document-delete'),

    path('products/<int:pk>/delete/',
         DashboardProductDeleteView.as_view(),
         name='product-delete'),

    path('posts/<int:pk>/delete/',
         DashboardPostDeleteView.as_view(),
         name='post-delete'),

    path('jobs/create/',
         DashboardJobCreateView.as_view(),
         name='job-create'),

    path('job/<int:pk>/update/',
         DashboardJobUpdateView.as_view(),
         name='job-update'),

    path('jobs/list/',
         DashboardJobsListView.as_view(),
         name='jobs-list'),

    path('resume/add/',
         DashboardResumeCreateView.as_view(),
         name='resume-create'),

    path('resume/<int:pk>/update/',
         DashboardResumeUpdateView.as_view(),
         name='resume-update'),

    path('product/create/',
         ProductCreateView.as_view(),
         name='product-create'),

    path('product/<int:pk>/update/',
         ProductUpdateView.as_view(),
         name='product-update'),

    path('services/create/',
         DashboardServiceCreateView.as_view(),
         name='service-create'),

    path('product/list/',
         DashboardProductListView.as_view(),
         name='products'),

    path('profile/update/',
         ProfileUpdateView.as_view(),
         name='profile-update'),

    path('posts/create/',
         DashboardPostCreateView.as_view(),
         name='post-create'),

    path('post/list/', DashboardPostListView.as_view(), name='posts'),
]

genoskul/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView
from us.views import PrivacyTemplateView, TermOfServiceTemplateView, AboutTemplateView
from genoskul.views import HomeTemplateView
from filebrowser.sites import site

admin.site.site_header = 'Site d\'administration de GENOSKUL'
admin.site.index_title = 'Panel administration GENOSKUL'
admin.site.site_title = 'GENOSKUL Admin'


urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('privacy/', PrivacyTemplateView.as_view(), name='privacy'),
    path('terms/', TermOfServiceTemplateView.as_view(), name='terms'),
    path('about/', AboutTemplateView.as_view(), name='about'),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),
    path('registration/', include('accounts.urls', namespace="accounts")),
    path('jobs/', include('jobs.urls', namespace="jobs")),
    path('learning/', include('learning.urls', namespace="learning")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('ndjor/', include('ndjor.urls', namespace="ndjor")),
    path('forum/', include('forum.urls', namespace="forum")),
    path('services/', include('services.urls', namespace="services")),
    path('admin/filebrowser/', site.urls),
    path('admin/staff/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path

from jobs.views import *

app_name = 'jobs'

urlpatterns = [
    path('list/',
         JobListView.as_view(), name='job-list'),
    path('resumes/list/', ResumeListView.as_view(), name='resume-list'),
    path('category/list/', CategoryListView.as_view(), name='category-list'),
    path('category/<int:pk>/detail/',
         CategoryDetailView.as_view(), name='category-detail'),
    path('resumes/<int:pk>/detail/',
         ResumeDetailView.as_view(), name='resume-detail'),
    path('<int:pk>/detail/', JobDetailView.as_view(), name='job-detail'),
]

ndjor/urls.py
from django.urls import path

from ndjor.views import ProductListView, ProductCategoryDetailView


app_name = 'ndjor'

urlpatterns = [
    path(
        'product/list/',
        ProductListView.as_view(), 
        name='product-list'),

    path(
        'category/<int:pk>/details/',
        ProductCategoryDetailView.as_view(),
        name='category-details'
    )
    
]

ndjor/models.py
from django.db import models
from django.db.models import Q
from django.contrib.auth import get_user_model
from genoskul.common.timestamp import TimeStampModel
from django.urls import reverse

User = get_user_model()


class ProductManager(models.Manager):
    def get_products(self, query=None):
        qs = self.get_queryset()
        if query:
            return qs.filter(
                Q(name__icontains=query) |
                Q(state__icontains=query) |
                Q(reference__icontains=query) |
                Q(location__icontains=query) |
                Q(price__icontains=query)
            )

        return qs



class ProductCategory(TimeStampModel):
    name = models.CharField(max_length=200, verbose_name='Nom de la catégorie')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("ndjor:category-details", kwargs={"pk": self.pk})
    
    class Meta:
        verbose_name = 'Catégorie de produit'
        verbose_name_plural = 'Catégories des produits'

class Product(TimeStampModel):
    name = models.CharField(max_length=100, verbose_name='Nom du produit')
    state = models.CharField(max_length=30, choices=(
        ('new', 'Neuf'), ('like_new', 'Comme Neuf'), ('others', 'Autres')), verbose_name='Etat du produit')
    category = models.ForeignKey(
        ProductCategory, on_delete=models.CASCADE, verbose_name='Catégorie du produit', related_name='products')
    reference = models.CharField(
        max_length=254, verbose_name='Contact du vendeur')
    image = models.ImageField(verbose_name='Photo de produit')
    owner = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='products', verbose_name='Propriétaire')
    location = models.CharField(max_length=30, verbose_name='Lieu de vente')
    price = models.CharField(max_length=30, blank=True, verbose_name='Prix' )

    objects = ProductManager()

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Produit'
        verbose_name_plural = 'Produits'

ndjor/forms.py
from django import forms

from ndjor.models import Product

class ProductModelForm(forms.ModelForm):
    class Meta: 
        model = Product
        fields = '__all__'
        exclude = ('owner', )

ndjor/views.py
from django.shortcuts import render
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy, reverse
from django.views.generic import (
    CreateView,
    ListView,
    UpdateView,
    DetailView
)

from ndjor.forms import ProductModelForm
from ndjor.models import Product, ProductCategory


class ProductCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    template_name = 'ndjor/product-form.html'
    form_class = ProductModelForm
    success_url = reverse_lazy('dashboard:product-create')
    success_message = "Votre produit a été ajouté avec succès !"

    def form_valid(self, form):
        obj = form.save(commit=False)
        obj.owner = self.request.user
        obj.save()
        return super().form_valid(form)


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Ajouter un produit'
        return context

class ProductListView(LoginRequiredMixin, ListView):
    template_name = 'ndjor/product-list.html'
    model = Product
    context_object_name = 'products'
    paginate_by = 20

    def get(self, request, *args, **kwargs):
        self.query = request.GET.get('query')
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.get_products(self.query)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Produits disponibles'
        context['query'] = self.query
        return context

class ProductUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    template_name = 'ndjor/product-form.html'
    form_class = ProductModelForm
    model = Product
    context_object_name = 'product'
    success_message = 'Votre produit a été mis à jour'

    def get_success_url(self):
        return reverse('dashboard:product-update', kwargs={'pk': self.kwargs.get('pk')})

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Modification du document'
        return context

class ProductCategoryDetailView(DetailView):
    template_name = 'ndjor/product-list.html'
    model = ProductCategory
    context_object_name  = 'category'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Les produits'
        return context

ndjor/templates/ndjor/product-form.html
{% extends "dashboard/base.html" %}

{% load crispy_forms_tags %}

{% block title %}
{{title}}
{% endblock title %}

{% block breadcrumb %}
<li>
    <a href="{% url 'dashboard:dashboard' %}">Tableau de bord</a>
</li>
<li>{{title}}</li>
{% endblock breadcrumb %}

{% block dashboard_content %}


<div class="row">

    <!-- Table-->
    <div class="col-lg-12 col-md-12">

        <form method="post" enctype="multipart/form-data">

            {% csrf_token %}

            <div class="dashboard-list-box margin-top-0">
                <h4>Informations sur le produit</h4>
                <div class="dashboard-list-box-content">

                    <div class="submit-page">

                        <div class="form">
                            {{form.name|as_crispy_field}}
                        </div>

                        <div class="form">
                            {{form.state|as_crispy_field}}</div>

                        <div class="form" style="width: 100%;">
                            {{form.category|as_crispy_field}}
                        </div>

                        <div class="form">
                            {{form.reference|as_crispy_field}}
                        </div>

                        <!-- Description -->
                        <div class="form">
                            {{form.image|as_crispy_field}}
                        </div>

                        <div class="form">
                            {{form.location|as_crispy_field}}
                        </div>
                        <div class="form">
                            {{form.price|as_crispy_field}}
                        </div>

                    </div>

                </div>
            </div>


            <button class="button margin-top-30" type="submit">{% if product %}
                Mettre a jour les modifications
                {% else %}
                Vendre mon produit
                {% endif %} </button>
        </form>

    </div>



</div>


{% endblock dashboard_content %}

ndjor/templates/ndjor/product-list.html
{% extends "base_site.html" %}

{% block title %}
{{title}}
{% endblock title %}

{% block breadcrumb-item %}
<li>{{title}}</li>
{% endblock breadcrumb-item %}

{% block content %}

<div class="container pb-5">
  <div class="row mb-4">
    <div class="col-12 col-md-6">
      <form action="{% url 'ndjor:product-list' %}" method="get" class="form-inline">
        <div class="form-group mb-0">
          <input type="text" name="query" value="{{query|default:''}}" class="form-control-sm rounded-0"
            placeholder="Rechercher un produit">
        </div>
        <button class="btn btn-primary btn-sm rounded-0" type="submit" style="margin-left: -5px">
          <i class="fa fa-search"></i>
        </button>
      </form>
      {% if query %}
      <p>Résultat de recherches pour: {{query}}</p>
      {% endif %}
    </div>
  </div>
  <div class="row">
    {% if category %}
    {% for product in category.products.all %}
    <div class="col-12 col-md-4 mb-3">
      {% include "ndjor/includes/product-single.html" with product=product %}
    </div>
    {% endfor %}
    {% else %}
    {% for product in products %}
    <div class="col-12 col-md-4 mb-3">
      {% include "ndjor/includes/product-single.html" with product=product %}
    </div>
    {% endfor %}
    {% endif %}
  </div>

  {% if is_paginated %}
  <div class="row">
    <div class="col-12 col-md-6">
      {% include "includes/pagination.html" %}
    </div>
  </div>
  {% endif %}

</div>

{% endblock content %}