dashboard/urls.py
from django.urls import path

from dashboard.views import *
from accounts.views import ProfileUpdateView
from ndjor.views import ProductCreateView, ProductUpdateView
from learning.views import DocumentCreateView
# from jobs.views import

app_name = 'dashboard'

urlpatterns = [
    path('', DashboardTemplateView.as_view(), name='dashboard'),
    path('documents/',
         DashboardDocumentListView.as_view(),
         name='documents'),
    path('document/create/',
         DocumentCreateView.as_view(),
         name='document-create'),

    path('document/<int:pk>/delete/',
         DashboardDocumentDeleteView.as_view(),
         name='document-delete'),

    path('products/<int:pk>/delete/',
         DashboardProductDeleteView.as_view(),
         name='product-delete'),

    path('posts/<int:pk>/delete/',
         DashboardPostDeleteView.as_view(),
         name='post-delete'),

    path('jobs/create/',
         DashboardJobCreateView.as_view(),
         name='job-create'),

    path('job/<int:pk>/update/',
         DashboardJobUpdateView.as_view(),
         name='job-update'),

    path('jobs/list/',
         DashboardJobsListView.as_view(),
         name='jobs-list'),

    path('resume/add/',
         DashboardResumeCreateView.as_view(),
         name='resume-create'),

    path('resume/<int:pk>/update/',
         DashboardResumeUpdateView.as_view(),
         name='resume-update'),

    path('product/create/',
         ProductCreateView.as_view(),
         name='product-create'),

    path('product/<int:pk>/update/',
         ProductUpdateView.as_view(),
         name='product-update'),

    path('services/create/',
         DashboardServiceCreateView.as_view(),
         name='service-create'),

    path('product/list/',
         DashboardProductListView.as_view(),
         name='products'),

    path('profile/update/',
         ProfileUpdateView.as_view(),
         name='profile-update'),

    path('posts/create/',
         DashboardPostCreateView.as_view(),
         name='post-create'),

    path('post/list/', DashboardPostListView.as_view(), name='posts'),
]

genoskul/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.views.generic.base import TemplateView
from us.views import PrivacyTemplateView, TermOfServiceTemplateView, AboutTemplateView
from genoskul.views import HomeTemplateView
from filebrowser.sites import site

admin.site.site_header = 'Site d\'administration de GENOSKUL'
admin.site.index_title = 'Panel administration GENOSKUL'
admin.site.site_title = 'GENOSKUL Admin'


urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('privacy/', PrivacyTemplateView.as_view(), name='privacy'),
    path('terms/', TermOfServiceTemplateView.as_view(), name='terms'),
    path('about/', AboutTemplateView.as_view(), name='about'),
    path('accounts/', include('allauth.urls')),
    path('dashboard/', include('dashboard.urls', namespace="dashboard")),
    path('registration/', include('accounts.urls', namespace="accounts")),
    path('jobs/', include('jobs.urls', namespace="jobs")),
    path('learning/', include('learning.urls', namespace="learning")),
    path('blog/', include('blog.urls', namespace="blog")),
    path('ndjor/', include('ndjor.urls', namespace="ndjor")),
    path('forum/', include('forum.urls', namespace="forum")),
    path('services/', include('services.urls', namespace="services")),
    path('admin/filebrowser/', site.urls),
    path('admin/staff/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

jobs/urls.py
from django.urls import path

from jobs.views import *

app_name = 'jobs'

urlpatterns = [
    path('list/',
         JobListView.as_view(), name='job-list'),
    path('resumes/list/', ResumeListView.as_view(), name='resume-list'),
    path('category/list/', CategoryListView.as_view(), name='category-list'),
    path('category/<int:pk>/detail/',
         CategoryDetailView.as_view(), name='category-detail'),
    path('resumes/<int:pk>/detail/',
         ResumeDetailView.as_view(), name='resume-detail'),
    path('<int:pk>/detail/', JobDetailView.as_view(), name='job-detail'),
]

jobs/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.urls import reverse

from genoskul.common.timestamp import TimeStampModel
from genoskul.common.validators import file_size

from jobs.managers import JobManager, ResumeManager

User = get_user_model()


class AbstractJob(TimeStampModel):
    name = models.CharField(max_length=50, verbose_name='Nom')

    def __str__(self):
        return self.name

    class Meta:
        abstract = True


class JobType(AbstractJob):
    class Meta:
        verbose_name = 'Type d\'emploi'
        verbose_name_plural = 'Types d\'emplois'


class JobCategory(AbstractJob):
    linear_icon = models.CharField(max_length=50, verbose_name='Icon')

    class Meta:
        verbose_name = 'Secteur d\'emploi'
        verbose_name_plural = 'Secteurs d\'emplois'

    def get_absolute_url(self):
        return reverse('jobs:category-detail', kwargs={'pk': self.pk})


class Company(TimeStampModel):
    name = models.CharField(max_length=100, verbose_name='Nom')
    website = models.URLField(blank=True, verbose_name='URL site internet')
    tagline = models.CharField(
        max_length=255, verbose_name='Brève description', blank=True)
    logo = models.ImageField(
        verbose_name='Logo', blank=True, null=True, validators=[file_size])

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Entreprise'
        verbose_name_plural = 'Entreprises'


class Job(TimeStampModel):
    title = models.CharField(max_length=200, verbose_name='Titre')
    type = models.ForeignKey(
        JobType, verbose_name='Type', on_delete=models.CASCADE)
    category = models.ManyToManyField(
        JobCategory, related_name='jobs', verbose_name='Secteur d\'emploi')
    location = models.CharField(
        max_length=100, verbose_name='Lieu d\'execution', blank=True)
    # tags = models.CharField(max_length=255, verbose_name='Tags', blank=True)
    description = models.TextField(verbose_name='Description du poste')
    application_email = models.EmailField(
        verbose_name='Adresse email de postulat')
    closing_date = models.DateField(
        verbose_name='Date de fermeture', blank=True, null=True)
    company = models.ForeignKey(
        Company, verbose_name='Entreprise', on_delete=models.CASCADE)
    user = models.ForeignKey(
        User, verbose_name='Créateur', related_name='jobs', on_delete=models.CASCADE)

    objects = JobManager()

    def get_absolute_url(self):
        return reverse("jobs:job-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = 'Offre d\'emploi'
        verbose_name_plural = 'Offres d\'emplois'


class Resume(TimeStampModel):
    pro_title = models.CharField(
        max_length=200, verbose_name='Titre professionel')
    location = models.CharField(
        max_length=150, verbose_name='Lieu de résidence')
    website = models.URLField(verbose_name='Lien du portfolio', blank=True)
    resume_file = models.FileField(
        verbose_name='Fichier CV', upload_to='resumes', validators=[file_size])

    contact = models.CharField(
        max_length=255, verbose_name='Votre contact', help_text='Aidez les récruteurs à vous contacter')

    description = models.TextField(verbose_name='A propos de vous')

    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name='resumes')

    objects = ResumeManager()

    def get_absolute_url(self):
        return reverse("jobs:resume-detail", kwargs={"pk": self.pk})

    def __str__(self):
        return '{} : {}'.format(self.pro_title, self.user.first_name)

jobs/forms.py
from django import forms

from jobs.models import Job, Resume, JobType, JobCategory


class JobModelForm(forms.ModelForm):
    # Company details form
    company_name = forms.CharField(
        label='Nom de l\'entreprise',
        widget=forms.TextInput(attrs={'placeholder': 'Entrez le nom de l\'entreprise'}))
    website = forms.URLField(label='Site internet',
                             required=False,
                             widget=forms.TextInput(
                                 attrs={'placeholder': 'https://'}))
    tagline = forms.CharField(
        label='Petite description', required=False, widget=forms.TextInput())
    logo = forms.ImageField(label='Logo de l\'entreprise', required=False,
                            widget=forms.FileInput())

    class Meta:
        model = Job
        exclude = ('company', 'user')
        widgets = {
            'description': forms.Textarea(attrs={'rows': 3}),
            'category': forms.SelectMultiple(
                attrs={'class': 'chosen-select', 'data-placeholder': 'Choisissez une catégorie'})
        }


class ResumeModelForm(forms.ModelForm):
    class Meta:
        model = Resume
        exclude = ('user',)
        widgets = {
            'description': forms.Textarea(attrs={'rows': 4}),
            'location': forms.TextInput(attrs={'placeholder': 'Ville/Pays'}),
            'pro_title': forms.TextInput(attrs={'placeholder': 'Votre compétence'}),
            'website': forms.TextInput(attrs={'placeholder': 'Entrez le lien de votre portfolio'}),
            'contact': forms.TextInput(attrs={'placeholder': 'Numéro de téléphone ou Adresse email'})
        }
        labels = {
            'resume_file': 'Joindre un CV'
        }



class JobFilterForm(forms.Form):
    type = forms.ChoiceField(
        required=False,
        label="Type de l'emploi",
        widget=forms.Select(attrs={
            'class': 'chosen-select-no-single',
            'data-placeholder': 'Choisissez un type'
        }))
    location = forms.CharField(
        required=False,
        label="Lieu d'exécution",
        widget=forms.TextInput(
            attrs={'placeholder': 'Entrez un nom de ville ou pays'})
    )

jobs/views.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import (
    ListView,
    DetailView
)

from accounts.models import Profile
from jobs.models import Job, Resume, JobCategory
from jobs.forms import ResumeModelForm, JobFilterForm


class JobListView(LoginRequiredMixin, ListView):
    template_name = 'jobs/jobs-list.html'
    model = Job
    context_object_name = 'jobs'
    paginate_by = 15

    def get(self, request, *args, **kwargs):
        self.type = request.GET.get('type', None)
        self.location = request.GET.get('location', None)
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.filter_by(self.type, self.location)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Liste des offres d\'emploi'
        context['form'] = JobFilterForm(self.request.GET)
        return context


class CategoryListView(ListView):
    template_name = 'jobs/category-list.html'
    model = JobCategory
    context_object_name = 'categories'
    paginate_by = 15


class CategoryDetailView(DetailView):
    template_name = 'jobs/jobs-list.html'
    model = JobCategory
    context_object_name = 'category'

    def get_object(self):
        return get_object_or_404(JobCategory, self.kwargs.get('pk'))


    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.get_object().name
        return context
        
    def get_object(self):
        return get_object_or_404(JobCategory, pk=self.kwargs.get('pk'))

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.get_object().name
        return context

    

class ResumeListView(LoginRequiredMixin, ListView):
    template_name = 'jobs/profile-list.html'
    model = Resume
    context_object_name = 'resumes'
    paginate_by = 20

    def get(self, request, *args, **kwargs):
        self.query = request.GET.get('query', None)
        return super().get(request, *args, **kwargs)

    def get_queryset(self):
        return self.model.objects.search(query=self.query)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Profils disponibles'
        if self.query:
            context['query'] = self.query
        return context

class ResumeDetailView(DetailView):
    template_name = 'jobs/profile-detail.html'
    model = Resume
    context_object_name = 'profile'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Details CV {}'.format(self.get_object().user.get_full_name)
        return context


class JobDetailView(DetailView):
    template_name = 'jobs/job-detail.html'
    model = Job
    context_object_name = 'job'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = self.get_object().title
        return context
    

jobs/templates/jobs/category-list.html
{% extends "base_site.html" %}

{% block title %}
  {{title}}
{% endblock title %}

{% block breadcrumb-item %}
  <li>Secteurs d'emploi disponibles</li>
{% endblock breadcrumb-item %}

{% block content %}
  
<div class="container py-4">

    <div class="categories-boxes-container">
				
        {% for category in categories %}
          {% include "jobs/includes/category-single.html" with category=category %}

          {% empty %}
          <p>Aucun secteur à lister !</p>
        {% endfor %}

    </div>

</div>

{% endblock content %}

jobs/templates/jobs/job-detail.html
{% extends "base_site.html" %}

{% load static %}

{% block title %}
{{title}}
{% endblock title %}

{% block breadcrumb-item %}
<li>
    <a href="{% url 'jobs:job-list' %}">Offres disponibles</a>
</li>
<li>{{title}}</li>
{% endblock breadcrumb-item %}

{% block content %}

<div class="container">

    <!-- Recent Jobs -->
    <div class="ten columns">
        <div class="padding-right">

            <!-- Company Info -->
            <div class="company-info">
                {% if job.company.logo %}
                <img src="{{job.company.logo.url}}" alt="{{job.title}}">
                {% else %}
                <img src="{% static 'images/logo-05.png' %}" alt="{{job.title}}">
                {% endif %}
                <div class="content">
                    <h4>{{job.company.name}}</h4>
                    <span><a href="{{job.company.website}}"><i class="fa fa-link"></i> Site internet</a></span>
                    <!-- <span><a href="#"><i class="fa fa-twitter"></i> @kingrestaurants</a></span> -->
                </div>
                <div class="clearfix"></div>
            </div>

            <p class="margin-reset">
                {{job.description|safe}}</p>



        </div>
    </div>


    <!-- Widgets -->
    <div class="five columns">

        <!-- Sort by -->
        <div class="widget">
            <h4>Vue d'ensemble</h4>

            <div class="job-overview">

                <ul>
                    <li>
                        <i class="fa fa-map-marker"></i>
                        <div>
                            <strong>Lieu d'execution:</strong>
                            <span>{{job.location}}</span>
                        </div>
                    </li>
                    <li>
                        <i class="fa fa-user"></i>
                        <div>
                            <strong>Titre de l'emploi</strong>
                            <span>{{job.title}}</span>
                        </div>
                    </li>

                </ul>


                <a href="mailto:{{job.application_email}}" class="btn btn-primary shadow-none btn-block">Postuler pour
                    cet offre</a>
            </div>

        </div>

    </div>


</div>


{% endblock content %}

jobs/templates/jobs/jobs-list.html
{% extends "base_site.html" %}

{% load static %}
{% load crispy_forms_tags %}

{% block title %}
{{title}}
{% endblock title %}

{% block breadcrumb-item %}
<li>
	<a href="{% url 'jobs:category-list' %}">Liste des secteurs d'emploi</a>
</li>
<li>{{title}}</li>
{% endblock breadcrumb-item %}

{% block content %}
<div class="container">

	<h3 class="mt-0 mb-2"><span class="text-primary text-uppercase">{{category.name}}</span></h3>

	<div class="ten columns">
		<div class="padding-right">

			<div class="listings-container">

				{% if category %}
				{% for job in category.jobs.all %}
				{% include "jobs/includes/job-single.html" with job=job %}
				{% empty %}

				<p class="primary">Aucune offre d'emploi à lister pour cet secteur !</p>

				{% endfor %}
				{% else %}
				{% for job in jobs %}
				{% include "jobs/includes/job-single.html" with job=job %}
				{% empty %}

				<p class="primary">Aucune offre d'emploi à lister !</p>

				{% endfor %}


				{% endif %}
				<!-- <a href="job-page.html" class="listing internship">
							<div class="listing-logo">
								<img src="images/job-list-logo-04.png" alt="">
							</div>
							<div class="listing-title">
								<h4>Power Systems User Experience Designer <span class="listing-type">Internship</span></h4>
								<ul class="listing-icons">
									<li><i class="ln ln-icon-Management"></i> Hexagon</li>
									<li><i class="ln ln-icon-Map2"></i> London</li>
									<li><i class="ln ln-icon-Money-2"></i> $55 / hour</li>
									<li><div class="listing-date">4d ago</div></li>
								</ul>
							</div>
						</a> -->

			</div>
			<div class="clearfix"></div>

			{% if is_paginated %}
			{% include "includes/pagination.html" %}
			{% endif %}

		</div>
	</div>
	{% if not category %}
	<div class="five columns">

		<div class="widget">
			<h4>Filtrer les offres</h4>

			<form method="get" action="{% url 'jobs:job-list' %}">
				{{form.type|as_crispy_field}}

				{{form.location|as_crispy_field}}

				<button class="btn btn-primary" type="submit">Filtrer</button>
			</form>

		</div>



	</div>


	{% endif %}


	<!-- Widgets / End -->


</div>

{% endblock content %}

jobs/templates/jobs/profile-detail.html
{% extends "base.html" %}

{% load static %}

{% block title %}
{{title}}
{% endblock title %}

{% block content %}
<div id="titlebar" class="resume">
    <div class="container">
        <div class="ten columns">
            <div class="resume-titlebar">
                {% with profile.user.profile as user_profile %}
                  {% if user_profile.avatar %}
                <img src="{{user_profile.avatar.url}}" alt="">
                    {% else %}
                <img src="{% static 'images/avatar-placeholder.png' %}" alt="">

                  {% endif %}
                {% endwith %}
                <div class="resumes-list-content">
                    <h4>{% if not profile.user.get_full_name %}
                        {{profile.user.get_username}}
                    {% endif %} {{profile.user.get_full_name}}<span>{{profile.pro_title}}</span></h4>
                    <span class="icons"><i class="fa fa-map-marker"></i> {{profile.location}}</span>
                    <!-- <span class="icons"><i class="fa fa-money"></i> $100 / hour</span> -->
                    <span class="icons"><a href="{{profile.website}}"><i class="fa fa-link"></i> Portfolio ou Site internet</a></span>
                    {% if profile.user.email %}
                    <span class="icons"><a href="mailto:{{profile.user.email}}"><i class="fa fa-envelope"></i>
                        {{profile.user.email}}</a></span>
                    {% endif %}
                    <!-- <div class="skills">
                        <span>JavaScript</span>
                        <span>PHP</span>
                        <span>WordPress</span>
                    </div> -->
                    <div class="clearfix"></div>

                </div>
            </div>
        </div>

        <div class="six columns">
            <div class="two-buttons">

                <a href="{{profile.resume_file.url}}" class="button"><i class="fa fa-download"></i> Télécharger son CV</a>

                <!-- <div id="small-dialog" class="zoom-anim-dialog mfp-hide apply-popup">
                    <div class="small-dialog-headline">
                        <h2>Send Message to John Doe</h2>
                    </div>

                    <div class="small-dialog-content">
                        <form action="#" method="get">
                            <input type="text" placeholder="Full Name" value="" />
                            <input type="text" placeholder="Email Address" value="" />
                            <textarea placeholder="Message"></textarea>

                            <button class="send">Send Application</button>
                        </form>
                    </div>

                </div>
                <a href="#" class="button dark"><i class="fa fa-star"></i> Bookmark This Resume</a> -->


            </div>
        </div>

    </div>
</div>



<div class="container">
    <div class="eight columns">
        <div class="padding-right">

            <h3 class="margin-bottom-15">A propos</h3>

            <p class="margin-reset">
                {{profile.description|safe}}
            </p>



        </div>
    </div>


</div>
{% endblock content %}

{% block footer %}
<div class="margin-top-45"></div>

{% include "base/footer.html" %}
{% endblock footer %}

jobs/templates/jobs/profile-list.html
{% extends "base_site.html" %}

{% block title %}
{{title}}
{% endblock title %}

{% block breadcrumb-item %}
<li>Profils disponibles </li>
{% endblock breadcrumb-item %}

{% block content %}

<div class="container">
    <div class="row">
        <div class="col-12 col-md-8 order-2 order-md-1">
            <div class="ten columns" style="">
                <a href="{% url 'dashboard:resume-create' %}" class="btn btn-primary btn-sm">Créer mon profil</a>
                <div class="padding-right">

                    <ul class="resumes-list alternative">

                        {% for resume in resumes %}
                        {% include "jobs/includes/profile-single.html" with profile=resume %}
                        {% empty %}
                        <p>Aucun profil trouvé !</p>
                        {% endfor %}

                    </ul>
                    <div class="clearfix"></div>

                    {% if is_paginated %}

                    {% include "includes/pagination.html" %}

                    {% endif %}

                </div>
            </div>
        </div>
        <div class="col-12 col-md-4 order-1 order-md-2">
            <div class="five columns">

                <div class="widget">
                    <h4>Rechercher</h4>

                    <form action="{% url 'jobs:resume-list' %}" method="get">
                        <input type="text" name="query" value="{{query}}" class="form-control"
                            placeholder="Entrez le motif de la recherche">
                        <button class="btn btn-primary">Rechercher</button>
                        

                </div>
            </div>

        </div>
    </div>



</div>

{% endblock content %}